// agregar a bobi bozman

export const RAPARTISTAS: any = [
    {name: 'Aleman', id: "4QFG9KrGWEbr6hNA58CAqE"},
    {name: 'Neto Peña', id: "0U5RYP2HMdGv2GhicLhkOI"},
    {name: 'Santa Fe', id: "4tm8CEdm4pkQsEh4jIr9Yp"},
    {name: 'Metrik Vader', id: "47zSpyjndukb8rBLQSSU3T"},
    {name: 'CKAN', id: "1QhaqxeqF9sipS2gwbEKpu"},
    {name: 'LNGSHT', id: "2q9p1IXueDbcN4de5C9fI2"},
    {name: 'AdanCruz', id: "645xd9cHiiLqqehoLzLMDR"},
    {name: 'Sr Marrano', id: "4TGavohrECqpfWpLz6QhkG"},
    {name: 'THRCru2', id: "7qfeRXz0fErzIordtUUxYn"},
    {name: 'EptosUno', id: "3fo4UvMNzZUCFS90Roh5iK"},
    {name: 'Mime 871', id: "3lrhy6KigCHdcc0vOSTWoI"},
    {name: 'Pato Machete', id: "0Wvud7hEqI5zaI0o0iIkj2"},
    {name: 'Control Machete', id: "628gUkswCfCS1hIOOHmIpK"},
    {name: 'Tino El Pinguino', id: "3BbLQNj5OTxm4AZcwyREFF"},
    {name: 'Boca Floja', id: "2bj9MQez88g09q4NSr2xjS"},
    {name: 'Akil Ammar', id: "6lOqlvNZmpkmHNN1Ud4KXr"},
    {name: 'West Gold', id: "1gPiNBRjOB9XochAAFR3iM"},
    {name: 'Robot', id: "30CTTIqrcr82nS6B40j975"},
    {name: 'Dharius', id: "66RfYVdftqnuHRicyClgL0"},
    {name: 'Hispana', id: "7rTmbfDJtDCjoy8XK5Dsj5"},
    {name: 'Cartel de Santa', id: "07PdYoE4jVRF6Ut40GgVSP"},
];

export const RAPARTISTAS2: any = [
    {name: 'Aczino', id: "4r1ZDYKzPt3iIjuq8LbT6X"},
    {name: 'Coko', id: "1txbs9MMkT4FszkaA96atm"},
    {name: 'Charles Ans', id: "5lYeiQxUTcGKVgAuTqbTeL"},
    {name: 'Gera Mx', id: "2hejA1Dkf8v8R0koF44FvW"},
    {name: 'Yoss Bones', id: "0SmgVe3giVHaJjGmIz8xA4"},
    {name: 'Tabernario', id: "2uG7vLSehD2quPeYSPkT73"},
    {name: 'WK', id: "7BQJLHBNVvz4O2JHmls4Ef"},
    {name: 'Mike Diaz', id: "5pR3pEU0bCMZhhAzag3DUz"},
    {name: 'Lefty SM', id: "6eXHRfK9Ad3IpMpSAqvcDf"},
    {name: 'T-Killa', id: "52QQ2BADyRwXsS8uqLu2Hl"},
    {name: 'Faruz Feet', id: "6tJRAxu0HwB2GI9GueEj4l"},
    {name: 'Spvce Problems', id: "0cyFixcJhYGoDQvgFOE2jq"},
    {name: 'Reno 871', id: "50nNZIMfSVOSOoZNPfgFCU"},
    {name: 'Achepe', id: "1b170j0PpkgYWGHMPRsNEM"},
    {name: 'Santa RM', id: "30BSBWLKnYJION1lCPugXc"},
    {name: 'Fntxy', id: "7I85Ma5xjAo6nlvqOCIiWx"},
    {name: 'Yoga Fire', id: "3AgxRYe2kXEfsZyB07hqJF"},
    {name: 'Anexo Leiruk', id: "4H3ePoFDdsl36QwB96jZzg"},
    {name: 'Millonario', id: "2N2aJ1SXQxMkhHD8C6fhYD"},
    {name: 'Tren Lokote', id: "6DjBv6gyR1HLsvwGUOD5V9"},
    {name: 'El Pinche Mara', id: "3L7OHIT4kfdcDSnnGM0TKN"},
];

export const RAPARTISTAS3: any = [
    {name: 'Geassasin', id: "4V2V4PaSblStayYVWTGDbZ"},
    {name: 'Logan Hate', id: "3duZndoIzAXtBJj8op4Abx"},
    {name: 'Dracks', id: "1zbQgvftfbVN7pPyNuR2U0"},
    {name: 'Phyz Eye', id: "1NsRsBdRV7uWMw0SYaHo01"},
    {name: 'Zaque', id: "4WQmw3fIx9F7iPKL5v8SCN"},
    {name: 'Muthahupa', id: "5i0eAAl4YhI6TmPodtseGi"},
    {name: 'Teeam Revolver', id: "5MRMYpdAWZawm3ivBeWvdK"},
    {name: 'Tiro Loko', id: "4Y5HJP3oFOJ8UVBXHYWBgx"},
    {name: 'Simspon ahuevo', id: "6viZnVSHavFUcW0blu6Mvw"},
    {name: 'Go Golden Junk', id: "2tU377oBzcCBbRNeVve8FC"},
    {name: 'Primero company', id: "6pu8qjuOYZRBYc1hiHEVL5"},
    {name: 'Tanke one', id: "6CJ0EnASyencrooPZNBpaB"},
    {name: 'Gino', id: "3BRcyV18jhoYQCCk0PJvrw"},
    {name: 'Montebel', id: "3n3xqTWiJ5cThzS3UsDQUV"},
    {name: 'Proof', id: "2Gcx4c9rFAAloAYV2cMGUd"},
    {name: 'Hadrian', id: "2F9icYS5KP4Td9nbxIjo9q"},
    {name: 'El pinche brujo', id: "1LjUlFOtTxcvWZQldBMSOW"},
    {name: 'Bull Montana', id: "2OprAdrzD4U2JTrL2XGvkL"},
    {name: 'Tonnie Rico', id: "4FnLpt7y15mESBAhQMAoad"},
    {name: 'Dasket Rapley', id: "3pW4tw2BArwIClCWHjJWVF"},
    {name: 'Little el Crack', id: "20kZ1fvR4TfMUsyXfOOnAm"},
];

export const RAPARTISTAS4: any = [
    {name: 'Leazzy', id: "4iPx95BzuqFwzfmIMPBC1p"},
    {name: 'Rabia Rivera', id: "1mKlMW38n3dOmsOIfaOaOU"},
    {name: 'Sociedad Cafe', id: "7FJZ5oy5kdpkqWYL2RGvRR"},
    {name: 'Turek Hem', id: "5HSROvpnFBzRENwjZ30RNx"},
    {name: 'Jay Romero', id: "4VECwDIJ0DYczPqCyP85kQ"},
    {name: 'Buffon', id: "7CvKsTEWv1BS3LydN8HgG6"},
    {name: 'Dharius', id: "66RfYVdftqnuHRicyClgL0"},
    {name: 'Remik', id: "4Hzj6dfl1y5x5TzCSsvLB6"},
    {name: 'Toser One', id: "1oHPSeQJBwNmpq0J52Wjn1"},
    {name: 'Under Side', id: "2NtN73hhhgFt2NmbBOlFz1"},
    {name: 'Mc Davo', id: "3TGeuw7OmACouH5JAKkX7I"},
    {name: 'Neto Reyno', id: "7sgnuH8OwU32WbGLZwD03q"},
    {name: 'Snow tha product', id: "3p3jPcp8b7WL9XYj4xlsWj"},
    {name: 'Ximbo', id: "0RjHsbbdfnI3okpxdZ2JOV"},
    {name: 'Vikcy MC', id: "2sF3CgV1tKubYGTUSKPenC"},
    {name: 'Zimple', id: "0l1OSQn6GtjfEE1Cb8LE1t"},
    {name: 'Zxmyr', id: "7IUaYyqcGB3aU2Tm4s5JY8"},
    {name: 'Lenin Pena', id: "3hWsyFI2fjSLqdHukSWzev"},
    {name: 'Zmoky', id: "3yxAI1UvJFajyxQ1eLf8gO"},
    {name: 'Guero Sosa', id: "4QYW33jqI9hiFLgJBPDvwU"},
    {name: 'Maythugs', id: "50rhEb0qCmiMkWEb3eN0rH"},
];

export const RAPARTISTAS5: any = [
    {name: 'Lirika Inverza', id: "214wdmDstodTL0SEEPDyxb"},
    {name: 'Bizor', id: "7F6fxMv0tz2Clj8H02Y2k7"},
    {name: 'Caballeros del plan g', id: "568lw0anJJJnjTXII3gHaf"},
    {name: 'Don Aereo', id: "2EkFEL5IvD2W8hpwbjS9yv"},
    {name: 'Kosmer', id: "2Ey4tRJ1hbrsMUn8GjhRn2"},
    {name: 'Doctor Destino', id: "5urer15JPbCELf17LVia7w"},
    {name: 'Danger Ak', id: "23TYM4mYLQjyJLr4x89MjH"},
    {name: 'Cozy Cuz', id: "3ScIigEm9KZUrUQtXzBmKJ"},
    {name: 'Maniako', id: "4XVWGb0bUVdiBhmWbSKSF3"},
    {name: 'Kstro MGA', id: "2cf3USXga99bsWQpBIcOl4"},
    {name: 'Cesaranderan', id: "3g3SX7D8ul0DxrOKlvjrKc"},
    {name: 'Perro ZW', id: "7CPuRgoqujB5wHULxqiIqv"},
    {name: 'Manicomio Plan', id: "4MU4o7Q9PEHnzuf1Kw5IBM"},
    {name: 'Nedman Guerrero', id: "216EDkKlBGRZUxVVhUwDll"},
    {name: 'Rhomer', id: "63YbwVzLF4i842NInZvY7J"},
    {name: 'Kidd M', id: "6hPRzsa6sYFIya5wOnzhzl"},
    {name: 'Mc Luka', id: "2HpeQd3eecBJ1cPR7SLcrP"},
    {name: 'Skool 77', id: "1XrrYgyQChyeEcHCG6AByX"},
    {name: 'Fermin IV', id: "74OPWhLPyLylAzgqcJlNMm"},
    {name: 'Gogo Ras', id: "0fCRMqA18mcwhcf5Rng0VF"},
    {name: 'Dee', id: "1jVhcHIGJuk16eqY1Mdtuk"},
];

export const RAPARTISTAS6: any = [
    {name: 'Industria City', id: "4r0vcc9R6J1ovqC8282rX3"},
    {name: 'Aguila Sativa', id: "7CrI6hfM0LP4jQkaTzdHbz"},
    {name: 'Masta Quba', id: "6huE8Sh7scgoA8rj2vCuwZ"},
    {name: 'Audry Funk', id: "7eWbFrseRms5D5quwPDkm2"},
    {name: 'Ogarita', id: "7F1M9d3MFyaMI7exRlfWsu"},
    {name: 'Ballin', id: "35BPWrbRCzHa7yWWvCi8BI"},
    {name: 'Escuela Sinica', id: "1jmpTEpfmOKFd90iLzjVeY"},
    {name: 'Mare Advertencia Lirika', id: "3QVB7ctBlqEFuQZeMDt6Qh"},
    {name: 'Bobi Bozman', id: "3N9ZhpiDCKh8UDpqf597SC"},
    {name: 'Fume 871', id: "4A0zvhdGzPzwgotxI5O3ci"},
    {name: 'Drvgs', id: "5VF9y2sGTphTF7jmXdplFu"},
    {name: 'Limbo Lowfi', id: "4EQWL5UyTdKnVQeIERcnpr"},
    {name: 'Doble P Ache Ene', id: "5yh17UV0XSFV1lzzFC39XR"},
    {name: 'Twisted Minded', id: "38nJKLU7rqAL9L2sJDniUH"},
    {name: 'Brez', id: "2jJmTEMkGQfH3BxoG3MQvF"},
    {name: 'Akwid', id: "3mYFuz6iY7D9X78rOXg5CG"},
    {name: 'Carlos Cartoon', id: "36FicGasyvKfn6whxEKdIS"},
    {name: 'Eric El Niño', id: "1PykidvCp6SM4KLJXDeprl"},
    {name: 'Yak MAg', id: "60IqCN3nOzZ13yd8dQy9cC"},
    {name: 'Bruno Grasso', id: "4fNQqyvcM71IyF2EitEtCj"},
    {name: 'Rapozt Mortem', id: "1KHXqOQxGsx47nQ3VsYCoy"},
];

export const RAPARTISTAS7: any = [
    {name: 'Justinani', id: "6daEHaxdKjnIGxdpeVRVMf"},
    {name: 'Malva', id: "1fKmFe01L78vPmmiJ10LAs"},
    {name: 'Menuda Coincidencia', id: "6qmixZxMYL2jroxAqPQvRe"},
    {name: 'La Banda Baston', id: "3vV4Tf1iC8vEP9fLOLGUfP"},
    {name: 'Spia 104', id: "49Q2I0njyI8l2nxCgXoGQ8"},
    {name: 'Jauría Santa', id: "662f8mEv1eRLXE9DzBy4vV"},
    {name: 'Solitario Mondragón', id: "4KXpp5lz2MakNFcTszi2B9"},
    {name: 'Bipo Montana', id: "6JG2QQcaQBzinELNvu9PRk"},
    {name: 'Caporal', id: "0lnkz75zUi8LVZeY8qd9tI"},
    {name: 'La Santa Grifa', id: "1oH2B8tcHn4Gpl2bmmyd4A"},
    {name: 'Playa Matafokas', id: "2xNpzwTQFG6D04SSTb32R1"},
];